# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
- UAT

pool:
  vmImage: ubuntu-latest

stages:
- stage: deploy
  displayName: deploy stage
  jobs: 
  - deployment: VMDeploy
    displayName: Moodle Deploy
    environment:
      name: CFM Rannlab Server
      resourceType: VirtualMachine
      tags: deploy
    strategy:
      rolling:
        deploy:
          steps:
          - checkout: git://MoodleLMS/MoodleLMS@UAT
            persistCredentials: true
          - script: |
                  cp -u -R $(Pipeline.Workspace)/s/* /home/elearngroup/public_html
                  chown elearngroup:elearngroup /home/elearngroup/public_html/* -R